=== mohosn/Nettverksprogrammering/Milepæl3+4/unshare-server/Group/poemdb.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="poemdb">
    <xs:complexType>
     <xs:choice maxOccurs="unbounded">
        <xs:element name="User">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="email"/>
              <xs:element name="password"/>
              <xs:element name="fname"/>
              <xs:element name="lname"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Session">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sessionID"/>
            <xs:element name="email"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Poem">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="poemID"/>
              <xs:element name="poem"/>
      		  <xs:element name="email"/>
      			</xs:sequence>
    		</xs:complexType>
  		</xs:element>
 		</xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mohosn/Nettverksprogrammering/Milepæl3+4/unshare-server/Group/poemdb.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="http://172.17.0.1/poemdb.xsl"?>
<poemdb xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://172.17.0.1/ poemdb.xsd">
  <User>
    <email>hu@gmail.com</email>
    <password>81dc9bdb52d04dc20036dbd8313ed055</password>
    <fname>hu</fname>
    <lname>The man</lname>
  </User>
  <Session>
    <sessionID>81dc9bdb52d04dc20036dbd8313ed055</sessionID>
    <email>mu@gmail.com</email>
  </Session>
  <Poem>
    <poemID>1</poemID>
    <poem>Hi</poem>
    <email>hu@gmail.com</email>
  </Poem>
  <Poem>
    <poemID>2</poemID>
    <poem>Hi</poem>
    <email>hu@gmail.com</email>
  </Poem>
</poemdb>
